version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '132852113'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db1:
    driver: local